### ISSUE TITLE
Can’t set border color

### ISSUE THREAD

**Issue by Linuus** [Ladicle/hydra-posframe#8]
Hi!

I can change the background color but the border color can't be changed. It just takes the same color as the background instead of what I specify in `hydra-posframe-border-face`.

My setup:
```elisp
    (use-package posframe)

    (use-package hydra-posframe
      :after hydra
      :straight (:host github :repo “Ladicle/hydra-posframe”)
      :hook (after-init . hydra-posframe-enable)
      :init
      (setq hydra-posframe-poshandler ‘posframe-poshandler-frame-bottom-center)
      (setq hydra-posframe-border-width 1)
      (setq hydra-posframe-parameters ‘((left-fringe . 5)(right-fringe . 5)))
      :custom-face (hydra-posframe-border-face ((t (:background “#bf616a”))))
      :custom-face (hydra-posframe-face ((t (:background “#3b4252”)))))
```
What it looks like:

https://preview.redd.it/79c0dmle04e41.png?width=308&format=png&auto=webp&s=d74f9a2ecf019dc320b1a3b3a532a395bc2144f5

Also, how can I change the fringe color in the posframe frame? I want it to be the same as the background color...

**Comment by Ladicle** [comment]
The border can now be displayed on macos.
fixed: https://github.com/Ladicle/hydra-posframe/commit/c6a86baa29043fa2e1ae912d539af70b374ffd50

<img width="1080" alt="image" src="https://user-images.githubusercontent.com/1159133/156006185-7f1b9f87-38db-4d56-9e26-2a67607fc5d9.png">

my setup:
```emacs-lisp
(leaf hydra-posframe
  :doc "Show hidra hints on posframe"
  :url "https://github.com/Ladicle/hydra-posframe"
  :if (window-system)
  :el-get "Ladicle/hydra-posframe"
  :global-minor-mode hydra-posframe-mode
  :custom
  (hydra-posframe-border-width . 5)
  (hydra-posframe-parameters   . '((left-fringe . 8) (right-fringe . 8)))
  :custom-face
  (hydra-posframe-border-face . '((t (:background "#323445")))))
```
